#server.port=9027
#spring.jpa.database=POSTGRESQL
#spring.sql.init.platform=postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/feenotifier
#spring.datasource.username=postgres
#spring.datasource.password=harjai702
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.show-sql=true
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
#spring.jpa.hibernate.naming.physical-strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
server:
  port: 9025
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: harjai702
    url: jdbc:postgresql://localhost:5432/feenotifier
    username: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  sql:
    init:
      platform: postgres
